name: "Performance Issue"
description: "Report performance issues with any solutions."
title: "performance: <brief description>"
labels: ["performance"]

assignees:
  - "mrasadatik"

body:
  - type: markdown
    attributes:
      value: |
        ## Performance Issue
        If a solution is inefficient or doesn't meet performance expectations, please report it here.

  - type: input
    attributes:
      label: Which solution has the performance issue?
      description: Specify which solution you're referring to.
      placeholder: e.g., Solution for Problem X
      required: true

  - type: input
    attributes:
      label: Describe the performance issue
      description: Explain the issue (e.g., slow runtime, high memory usage).
      placeholder: e.g., The solution takes too long on large inputs.
      required: true

  - type: input
    attributes:
      label: Expected performance
      description: What would the expected performance be?
      placeholder: e.g., The solution should run within O(n log n) time complexity.
      required: true

  - type: input
    attributes:
      label: Actual performance
      description: What is the observed performance?
      placeholder: e.g., The solution runs in O(n^2) time complexity.
      required: true

  - type: input
    attributes:
      label: Suggested improvements (optional)
      description: If you have any suggestions to improve performance, please share.
      placeholder: Optional
      required: false
