name: "Security Vulnerability Report"
description: "Report any security vulnerabilities or risks."
title: "security: <brief description>"
labels: ["security"]

assignees:
  - "mrasadatik"

body:
  - type: markdown
    attributes:
      value: |
        ## Security Issue
        If you've identified a security vulnerability, please report it here.

  - type: input
    attributes:
      label: Description of the security issue
      description: Describe the security vulnerability.
      placeholder: e.g., The solution does not sanitize user input.
      required: true

  - type: input
    attributes:
      label: Impact of the vulnerability
      description: Explain how this vulnerability could be exploited.
      placeholder: e.g., This could allow code injection.
      required: true

  - type: input
    attributes:
      label: Steps to reproduce
      description: How can we verify or reproduce the issue?
      placeholder: e.g., Submit malicious input to the solution.
      required: true

  - type: input
    attributes:
      label: Suggested fix (optional)
      description: If you have a fix, please provide it.
      placeholder: Optional
      required: false
